# Generated by Django 4.0.4 on 2022-04-22 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=50, verbose_name='Jmeno alba')),
                ('a_rok', models.IntegerField(max_length=50)),
            ],
            options={
                'ordering': ['a_name'],
            },
        ),
        migrations.CreateModel(
            name='Interpret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Jmeno interpreta')),
                ('text', models.TextField(verbose_name='Info k interpretovi')),
                ('startYear', models.IntegerField(blank=True, max_length=50, null=True)),
                ('narodnost', models.CharField(max_length=50, verbose_name='Narodnost')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zanr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jzanr', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['jzanr'],
            },
        ),
        migrations.CreateModel(
            name='Pisen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50, verbose_name='Nazev pisne')),
                ('p_writer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Skladatel')),
                ('p_lyrics', models.TextField(blank=True, null=True, verbose_name='Text pisne')),
                ('p_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album', verbose_name='Album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='autor_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.interpret', verbose_name='Interpret'),
        ),
        migrations.AddField(
            model_name='album',
            name='zanr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.zanr', verbose_name='Zanr'),
        ),
    ]
