# Generated by Django 4.0.4 on 2022-05-29 18:28

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pisen',
            options={'ordering': ['p_name']},
        ),
        migrations.AddField(
            model_name='album',
            name='a_foto',
            field=models.FileField(blank=True, null=True, upload_to=music.models.cover_path, verbose_name='Cover alba'),
        ),
        migrations.AlterField(
            model_name='interpret',
            name='startYear',
            field=models.IntegerField(blank=True, help_text='Zadej rok', max_length=50, null=True, verbose_name='Vznik kapely'),
        ),
    ]
